"""initial schema with all models

Revision ID: 3f7aa655bba4
Revises: 
Create Date: 2026-02-28 18:37:53.663370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f7aa655bba4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', name='subscriptiontier'), nullable=False),
    sa.Column('sector_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('startups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('score_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('signals_status', sa.String(length=20), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_startups_name'), 'startups', ['name'], unique=False)
    op.create_index(op.f('ix_startups_sector'), 'startups', ['sector'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('HIRING', 'LINKEDIN', name='signaltype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_startup_id'), 'signals', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_startup_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_startups_sector'), table_name='startups')
    op.drop_index(op.f('ix_startups_name'), table_name='startups')
    op.drop_table('startups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
